# Site settings
title: Matthew Solomon Moroney
description: Matthew Solomon Moroney
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Matthew Moroney
user_description: I am a second year Masters of Environmental student open to employment ozpportunities, new ventures, and collaborations. My work uses data to mobilize green venture capital to accelerate the transition to a decarbonized, less toxic, and just society. I do this by connecting green chemistry, the circular economy, and data-driven decision making.

user_title: Environmental Management with Data & Creativity
email: matthew.moroney@yale.edu
twitter_username: nourishideas
github_username:  greenisagoodcolor

# Google-analytics
google-analytics:
  id: ""
 
exclude: ['package.json', 'src' , 'node_modules']
